# These are supported funding model platforms

github: ParsaSmahmoudi
patreon: ParsaSmahmoudi
open_collective: hyperion-llm
ko_fi: parsa
tidelift: hyperion
community_bridge: hyperion
liberapay: parsa
issuehunt: ParsaSmahmoudi
otechie: hyperion
custom: ["https://buymeacoffee.com/parsa"]
